export const images = {
  easy: [
    "/images/argentina.png",
    "/images/brazil.png",
    "/images/germany.png",
    "/images/france.png",
    "/images/spain.png",
    "/images/portugal.png",
  ],
  normal: [
    "/images/morocco.png",
    "/images/algeria.png",
    "/images/iran.png",
    "/images/japan.png",
    "/images/usa.png",
    "/images/china.png",
    "/images/italy.png",
    "/images/russia.png",
  ],
  hard: [
    "/images/brazil.png",
    "/images/canada.png",
    "/images/germany.png",
    "/images/france.png",
    "/images/spain.png",
    "/images/qatar.png",
    "/images/colombia.png",
    "/images/uruguay.png",
    "/images/south-africa.png",
    "/images/croatia.png",
  ],
};
